# =======================
#     LIBRARY make
# =======================


SUBDIRS =  TEMPORAL_EVOLUTION_DETERMINISTIC  TEMPORAL_EVOLUTION_STOCHASTIC   


.PHONY: subdirs $(SUBDIRS)
     
subdirs: $(SUBDIRS)


$(SUBDIRS):
	$(MAKE) -C $@


